# Generated by Django 4.2.6 on 2024-02-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('messemail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_time', models.DateTimeField(auto_now=True, verbose_name='Последняя отправка рассылки')),
                ('status', models.CharField(max_length=6, verbose_name='Статус отправки рассылки')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рассылки')),
                ('creation_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('interval', models.CharField(choices=[('every_minute', 'Каждую минуту'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], default='daily', max_length=15, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('enabled', 'Активна'), ('disabled', 'Неактивна')], default='enabled', max_length=8, verbose_name='Статус рассылки')),
                ('next_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней отправки')),
                ('customers', models.ManyToManyField(to='customers.customer', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100, verbose_name='Тема рассылки')),
                ('body', models.TextField(verbose_name='Содержание рассылки')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='messemail.message', verbose_name='Сообщение'),
        ),
    ]
