# Generated by Django 4.2.6 on 2024-02-11 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 21, 48, 46, 849391), verbose_name='Дата создания'),
        ),
    ]
