# Generated by Django 4.2.6 on 2024-02-12 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 21, 28, 47, 537505), verbose_name='Дата создания'),
        ),
    ]
